Repository WildCodeSchool/orleans-0218-entreloups, pull requests merged in 2018-06, with the labels that each got.

#45 S2 us7 create event
  app/Resources/views/event/new.html.twig
  src/AppBundle/Entity/Event.php
Labels: Reviewed By PO

#47 Passage du site en français pour les messages d'erreur
  app/config/config.yml
Labels: Reviewed By PO

#48 Fix d'un souci de répétition du motif gradient du background
  assets/scss/main.scss
Labels: Reviewed By PO

#43 S2 us9 edit event admin
  app/Resources/views/event/edit.html.twig
  assets/js/app.js
Labels: Correction Done, Reviewed By PO

#58 Tag crud
  app/Resources/views/tag/edit.html.twig
  app/Resources/views/tag/index.html.twig
  app/Resources/views/tag/new.html.twig
  app/Resources/views/tag/show.html.twig
  src/AppBundle/Controller/TagController.php
  src/AppBundle/Entity/Tag.php
  src/AppBundle/Form/TagType.php
  src/AppBundle/Repository/TagRepository.php
  src/AppBundle/Tests/Controller/TagControllerTest.php
Labels: Reviewed By PO

#46 S2 us11 mise en forme evenement visiteur
  app/Resources/views/event/show.html.twig
  assets/scss/event.scss
  assets/scss/home.scss
Labels: Reviewed By PO

#59 Fix du background du body
  assets/scss/main.scss
Labels: Reviewed By PO

#60 ajout lien twig pour description
  app/Resources/views/event/show.html.twig
Labels: Reviewed By PO

#66 Génération de l'entité Notification et de son CRUD
  app/Resources/views/notification/edit.html.twig
  app/Resources/views/notification/index.html.twig
  app/Resources/views/notification/new.html.twig
  app/Resources/views/notification/show.html.twig
  src/AppBundle/Controller/NotificationController.php
  src/AppBundle/Entity/Notification.php
  src/AppBundle/Form/NotificationType.php
  src/AppBundle/Repository/NotificationRepository.php
  src/AppBundle/Tests/Controller/NotificationControllerTest.php
Labels: Reviewed By PO

#75 Role with crud
  app/Resources/views/role/edit.html.twig
  app/Resources/views/role/index.html.twig
  app/Resources/views/role/new.html.twig
  app/Resources/views/role/show.html.twig
  src/AppBundle/Controller/RoleController.php
  src/AppBundle/Entity/Role.php
  src/AppBundle/Form/RoleType.php
  src/AppBundle/Repository/RoleRepository.php
  src/AppBundle/Tests/Controller/RoleControllerTest.php
Labels: Reviewed By PO

#76 Changement de background
  assets/scss/main.scss
Labels: Reviewed By PO

#79 S3 us13 role crud on same page
  app/Resources/views/role/edit.html.twig
  app/Resources/views/role/index.html.twig
  app/Resources/views/role/new.html.twig
  app/Resources/views/role/show.html.twig
  src/AppBundle/Controller/RoleController.php
  src/AppBundle/Form/RoleType.php
Labels: Reviewed By PO

#84 S3 us16 upload
  app/AppKernel.php
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/show.html.twig
  app/config/config.yml
  composer.json
  composer.lock
  package-lock.json
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Form/EventType.php
Labels: Reviewed By PO

#82 S3 us17 add notification to one edition
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/show.html.twig
  app/Resources/views/notification/new.html.twig
  app/config/services.yml
  assets/scss/edition.scss
  composer.json
  composer.lock
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Notification.php
  src/AppBundle/Form/NotificationType.php
  webpack.config.js
Labels: Reviewed By PO

#85 Fix vue edit apres fonction upload
  app/Resources/views/event/edit.html.twig
  src/AppBundle/Form/EventType.php
Labels: Reviewed By PO

#89 ajout de la police
  assets/scss/main.scss
Labels: Reviewed By PO

#91 fix h5 sur Event/index et la couleur du titre de la page
  app/Resources/views/event/index.html.twig
  assets/scss/event.scss
Labels: Reviewed By PO

#92 fix padding footer fixed
  assets/scss/main.scss
Labels: Correction Done

#80 S3 us14 tag relies aux events
  app/Resources/views/base.html.twig
  app/Resources/views/event/edit.html.twig
  app/config/config.yml
  app/config/services.yml
  assets/css/tagsinput.css
  assets/js/app.js
  assets/js/tagsinput.js
  assets/js/typeahead.bundle.js
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Controller/TagController.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/Tag.php
  src/AppBundle/Form/DataTransformer/TagsToCollectionTransformer.php
  src/AppBundle/Form/EventType.php
  src/AppBundle/Form/TagType.php
  src/AppBundle/Tests/Form/DataTransformer/TagsToCollectionTransformerTest.php
  tests/AppBundle/Controller/DefaultControllerTest.php
  var/SymfonyRequirements.php
  webpack.config.js
Labels: Reviewed By PO

#83 Uniformisation des formulaires
  app/Resources/FOSUserBundle/views/ChangePassword/change_password_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  app/Resources/FOSUserBundle/views/Security/login_content.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/new.html.twig
  src/AppBundle/Form/EditionType.php
  src/AppBundle/Form/ProfileType.php
  src/AppBundle/Form/RegistrationType.php
Labels: Correction Done

#97 Fix Image uploadé
  app/Resources/views/event/edit.html.twig
  assets/js/app.js
  src/AppBundle/Form/EventType.php
Labels: Reviewed By PO

#96 Fix titles
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/edition/show.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/legal_notice/legal_notice.html.twig
  app/Resources/views/role/index.html.twig
  app/Resources/views/tag/edit.html.twig
  app/Resources/views/tag/index.html.twig
  app/Resources/views/tag/new.html.twig
  app/Resources/views/tag/show.html.twig
Labels: Reviewed By PO

#100 décalage du bouton et changement de couleur
  app/Resources/views/event/show.html.twig
Labels: Reviewed By PO

#101 ajout de la balise title sur les boutons
  app/Resources/views/event/index.html.twig
Labels: Reviewed By PO

#102 Multifix 120618
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/footer.html.twig
  assets/scss/main.scss
Labels: Correction Done

#99 S4 us18 edition visiteur
  app/Resources/views/base.html.twig
  app/Resources/views/edition/show.html.twig
  assets/scss/main.scss
Labels: Reviewed By PO

#104 Fix buttons event show
  app/Resources/views/event/show.html.twig
  composer.lock
Labels: Reviewed By PO

#115 S5 us21 to do list
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/task/new.html.twig
  src/AppBundle/Controller/TaskController.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Task.php
  src/AppBundle/Form/TaskType.php
  src/AppBundle/Repository/TaskRepository.php
Labels: Reviewed By PO

#126 S5 us24 delete task
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/task/edit.html.twig
  src/AppBundle/Controller/TaskController.php
Labels: Reviewed By PO

#127 Correction responsive + taille card
  app/Resources/views/edition/edit.html.twig
  assets/scss/edition.scss
Labels: Reviewed By PO

#130 Ajout de la navigation entre les éditions et les events
  app/Resources/views/event/edit.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Form/EditionType.php
Labels: Reviewed By PO

#132 Ajout de la liste des éditions sous forme de link
  app/Resources/views/event/edit.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/EventController.php
Labels: Reviewed By PO

#134 Fix suite à une disparition de certains éléments
  app/Resources/views/edition/edit.html.twig
Labels: Reviewed By PO

#138 S5 us27 search user
  app/Resources/views/user/searchUser.html.twig
  src/AppBundle/Controller/UserController.php
  src/AppBundle/Form/UserType.php
Labels: Change Requested

#140 Fix html validator
  app/Resources/FOSUserBundle/views/ChangePassword/change_password.html.twig
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/FOSUserBundle/views/layout.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/index.html.twig
  app/Resources/views/notification/edit.html.twig
  app/Resources/views/notification/index.html.twig
  app/Resources/views/notification/new.html.twig
  app/Resources/views/notification/show.html.twig
  assets/scss/main.scss
  src/AppBundle/Form/EventType.php
Labels: Reviewed By PO

#133 S5 us22 search bar
  app/Resources/views/default/index.html.twig
  app/Resources/views/event/events.html.twig
  app/Resources/views/event/index.html.twig
  assets/scss/event.scss
  assets/scss/home.scss
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/HomeController.php
  src/AppBundle/DataFixtures/EventFixtures.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/Tag.php
  src/AppBundle/Form/SearchType.php
  src/AppBundle/Repository/EventRepository.php
Labels: Correction Done, Reviewed By PO

#142 DevToMaster
  app/Resources/FOSUserBundle/views/ChangePassword/change_password.html.twig
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/FOSUserBundle/views/layout.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/index.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/events.html.twig
  app/Resources/views/event/index.html.twig
  app/Resources/views/notification/edit.html.twig
  app/Resources/views/notification/index.html.twig
  app/Resources/views/notification/new.html.twig
  app/Resources/views/notification/show.html.twig
  app/Resources/views/task/edit.html.twig
  app/Resources/views/task/new.html.twig
  app/Resources/views/user/searchUser.html.twig
  assets/scss/edition.scss
  assets/scss/event.scss
  assets/scss/home.scss
  assets/scss/main.scss
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Controller/HomeController.php
  src/AppBundle/Controller/TaskController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/DataFixtures/EventFixtures.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/Tag.php
  src/AppBundle/Form/EditionType.php
  src/AppBundle/Form/EventType.php
  src/AppBundle/Form/SearchType.php
  src/AppBundle/Form/UserType.php
  src/AppBundle/Repository/EventRepository.php
Labels: Reviewed By PO

#143 Fix tag to mot clé
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/events.html.twig
  app/Resources/views/event/new.html.twig
  src/AppBundle/Form/SearchType.php
Labels: Reviewed By PO

#144 fix redirection des boutons retour
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/task/new.html.twig
  src/AppBundle/Controller/EditionController.php
Labels: Reviewed By PO

#145 fix datepicker champ vide
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Task.php
Labels: Reviewed By PO

#146 DevToMaster
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/events.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/task/new.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Task.php
  src/AppBundle/Form/SearchType.php
Labels: Reviewed By PO

#150 S6 us30 group entity
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/group/index.html.twig
  app/Resources/views/group/new.html.twig
  src/AppBundle/Controller/GroupController.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Group.php
  src/AppBundle/Entity/Role.php
  src/AppBundle/Form/GroupType.php
  src/AppBundle/Repository/GroupRepository.php
Labels: Reviewed By PO

#159 listing des évènements du créateur sur la page 'mon compte'
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/User.php
Labels: Reviewed By PO

#168 ajout du service de slug et changement des routes d'évènements
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/events.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/EventController.php
  src/AppBundle/DataFixtures/EventFixtures.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Service/SlugService.php
Labels: Reviewed By PO

#173 S6 us19
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  assets/js/searchCity.js
  package-lock.json
  package.json
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/ProfileType.php
  src/AppBundle/Form/RegistrationType.php
Labels: Reviewed By PO

#177 changement du nom de variable de la recherche par tag
  app/Resources/views/event/events.html.twig
  src/AppBundle/Controller/HomeController.php
Labels: Reviewed By PO

#178 S6 us32 choose tags
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Tag.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/ProfileType.php
  src/AppBundle/Form/RegistrationType.php
Labels: Reviewed By PO

#179 Ajout de l'entry dans webpackconfig
  webpack.config.js
Labels: Reviewed By PO

#180 fix route card
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
Labels: Reviewed By PO

#181 S6 us28 attribution role to user
  app/Resources/views/group/index.html.twig
  app/Resources/views/group/new.html.twig
  app/Resources/views/user/invite.html.twig
  src/AppBundle/Controller/GroupController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/Entity/Group.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/InvitationType.php
  src/AppBundle/Form/UserType.php
  src/AppBundle/Repository/GroupRepository.php
Labels: Reviewed By PO

#182 modification de la vue après inscription
  app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig
Labels: Reviewed By PO

#183 petit fix sur les groups, cas empty
  src/AppBundle/Controller/UserController.php
Labels: Reviewed By PO

#184 cas où user non inscrit
  app/Resources/views/user/invite.html.twig
  src/AppBundle/Controller/UserController.php
Labels: Reviewed By PO

#191 Affichage de la liste des éditions passées et à venir d'un événement
  app/Resources/views/event/show.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/EventController.php
Labels: Reviewed By PO

#198 Ajout bouton gestion event
  app/Resources/views/event/show.html.twig
  src/AppBundle/Controller/EventController.php
Labels: Reviewed By PO

#204 Ajout bouton gestion edition
  app/Resources/views/edition/show.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Service/CheckUserRole.php
Labels: Correction Done, Reviewed By PO

#210 S6 us29 mail invitation
  app/Resources/views/mail/invitation.html.twig
  app/config/config.yml
  src/AppBundle/Controller/UserController.php
  src/AppBundle/Service/Mailer.php
Labels: Reviewed By PO

#209 fix_showEditionStatus
  app/Resources/views/edition/show.html.twig
  src/AppBundle/Controller/EditionController.php
Labels: Conflicts

#212 ajout du bouton de création d'évènement et suppression du bouton d'ac…
  app/Resources/views/base.html.twig
Labels: Reviewed By PO

#211 S6 us39 slug edition
  app/Resources/views/edition/index.html.twig
  app/Resources/views/event/edit.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Entity/Edition.php
Labels: Conflicts

#197 Ajout de champs dans l'entité Event et modifications des vues assiocées
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/show.html.twig
  assets/js/eventCity.js
  src/AppBundle/Entity/Event.php
  src/AppBundle/Form/EventType.php
  webpack.config.js
Labels: Correction Done, Reviewed By PO

#214 correctif route slug/id et swiftmailer service
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/views/edition/show.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/group/index.html.twig
  app/Resources/views/task/new.html.twig
  app/config/services.yml
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/TaskController.php
  src/AppBundle/Controller/UserController.php
Labels: Reviewed By PO

#215 Fixde l'edit de l'user
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/views/event/edit.html.twig
  assets/js/eventCity.js
  package-lock.json
  src/AppBundle/Form/ProfileType.php
Labels: Reviewed By PO

#213 gestion des dates de fin inférieur aux dates de début de l'edition
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  src/AppBundle/Controller/EditionController.php
Labels: Correction Done

#218 Transformation des checkboxes de tags en toggles sur 3 colonnes
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  assets/js/toggles.js
  assets/scss/toggleStyle.scss
  webpack.config.js
Labels: Reviewed By PO

#222 Verrouillage route
  app/config/security.yml
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Service/CheckUserRole.php
Labels: Reviewed By PO

#219 Fix one for all
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/new.html.twig
  assets/js/eventCity.js
  assets/js/searchCity.js
  webpack.config.js
Labels: Reviewed By PO

#223 ajout des fixtures edition notification role tag task and user
  src/AppBundle/DataFixtures/EditionFixtures.php
  src/AppBundle/DataFixtures/EventFixtures.php
  src/AppBundle/DataFixtures/NotificationFixtures.php
  src/AppBundle/DataFixtures/RoleFixtures.php
  src/AppBundle/DataFixtures/TagFixtures.php
  src/AppBundle/DataFixtures/TaskFixtures.php
  src/AppBundle/DataFixtures/UserFixtures.php
Labels: Reviewed By PO

#224 Fix auto complete tag after verrou
  app/config/security.yml
  assets/js/app.js
  src/AppBundle/Controller/HomeController.php
  src/AppBundle/Controller/TagController.php
Labels: Reviewed By PO

#225 Fix route creator group
  src/AppBundle/Service/CheckUserRole.php
Labels: Reviewed By PO
