Repository WildCodeSchool/orleans-0218-entreloups, pull requests merged in 2018-07, with the labels that each got.

#231 Message flash invitation gestionnaire
  app/Resources/views/user/invite.html.twig
  src/AppBundle/Controller/UserController.php
Labels: Reviewed By PO

#232 S7 us20 follow event
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/mail/notification.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Service/Mailer.php
Labels: Reviewed By PO

#236 suppression des messages flash dans les vues twig
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
Labels: Reviewed By PO

#239 suppression d'une méthode et de fichiers inutilisés
  app/Resources/views/notification/edit.html.twig
  app/Resources/views/notification/index.html.twig
  app/Resources/views/notification/new.html.twig
  app/Resources/views/notification/show.html.twig
  app/Resources/views/user/searchUser.html.twig
  src/AppBundle/Controller/NotificationController.php
  src/AppBundle/Controller/UserController.php
Labels: Reviewed By PO

#237 ajout du message flash dans base
  app/Resources/views/base.html.twig
Labels: Reviewed By PO

#238 changement des labels d'invitation
  app/Resources/views/group/index.html.twig
  app/Resources/views/user/invite.html.twig
Labels: Reviewed By PO

#242 desinstall composer 1.5 pour 1.6.5
  composer.lock
Labels: Reviewed By PO

#240 Readme
  README.md
  package-lock.json
  web/Accueil.png
Labels: Reviewed By PO

#243 gestion des asserts unique
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/Role.php
  src/AppBundle/Entity/User.php
Labels: Reviewed By PO

#244 remove current password field my account
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  src/AppBundle/Form/ProfileType.php
Labels: Change Requested

#245 changement du message de bienvenue
  app/Resources/views/default/index.html.twig
Labels: Reviewed By PO

#249 S7 us41 edit notifications
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/notification/edit.html.twig
  src/AppBundle/Controller/NotificationController.php
Labels: Reviewed By PO

#259 changement du viewport
  app/Resources/views/base.html.twig
Labels: Reviewed By PO

#254 refactorisation de l'affichage des events en passant par la vue dédié…
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
Labels: Conflicts

#252 S7 us40 delete notifications
  app/Resources/views/edition/edit.html.twig
  src/AppBundle/Controller/NotificationController.php
Labels: Reviewed By PO

#253 impossibilité de supprimer un event s'il contient une edition, avec m…
  src/AppBundle/Controller/EventController.php
Labels: Reviewed By PO

#260 ajout de la class confirm alert pour avoir un message de confirmation…
  app/Resources/views/role/index.html.twig
Labels: Reviewed By PO

#261 Fix edition edit buttons
  app/Resources/views/base.html.twig
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/event/edit.html.twig
  assets/scss/edition.scss
  src/AppBundle/Form/EditionType.php
Labels: Reviewed By PO

#258 S7 us43 proximity event
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/event/events.html.twig
  app/Resources/views/event/proximity_events.html.twig
  assets/js/rangeValue.js
  assets/scss/toggleStyle.scss
  package-lock.json
  package.json
  src/AppBundle/Controller/EventController.php
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/ProfileType.php
  src/AppBundle/Form/RegistrationType.php
  src/AppBundle/Repository/EventRepository.php
  src/AppBundle/Service/CheckDistance.php
  webpack.config.js
Labels: Reviewed By PO

#266 suppression de l'affichage du message d'erreur si les events ne sont …
  app/Resources/views/default/index.html.twig
  app/Resources/views/event/events.html.twig
Labels: Reviewed By PO

#267 fix responsive mobile
  app/Resources/views/group/index.html.twig
Labels: Reviewed By PO

#269 DevToMaster
  README.md
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/edition/edit.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/events.html.twig
  app/Resources/views/event/proximity_events.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/group/index.html.twig
  app/Resources/views/mail/notification.html.twig
  app/Resources/views/notification/edit.html.twig
  app/Resources/views/notification/index.html.twig
  app/Resources/views/notification/new.html.twig
  app/Resources/views/notification/show.html.twig
  app/Resources/views/role/index.html.twig
  app/Resources/views/user/invite.html.twig
  app/Resources/views/user/searchUser.html.twig
  assets/js/rangeValue.js
  assets/scss/edition.scss
  assets/scss/toggleStyle.scss
  composer.lock
  package-lock.json
  package.json
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Controller/NotificationController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/Role.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/EditionType.php
  src/AppBundle/Form/ProfileType.php
  src/AppBundle/Form/RegistrationType.php
  src/AppBundle/Repository/EventRepository.php
  src/AppBundle/Service/CheckDistance.php
  src/AppBundle/Service/Mailer.php
  web/Accueil.png
  webpack.config.js
Labels: Reviewed By PO

#268 ajout de classes bootstrap pour le responsive
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
Labels: Denied By Nono

#270 Fix event new responsive
  app/Resources/views/event/new.html.twig
Labels: Reviewed By PO

#271 Harmonistation de la barre de slide
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  assets/scss/rangeStyle.scss
  webpack.config.js
Labels: Reviewed By PO

#272 correction de l'affichage mobile de event_show
  app/Resources/views/event/show.html.twig
Labels: Reviewed By PO

#273 ajout de classes bootstrap pour le responsive
  app/Resources/views/event/edit.html.twig
Labels: Reviewed By PO

#276 ajout de suppression des participants pour le createur uniquement
  app/Resources/views/group/index.html.twig
  src/AppBundle/Controller/GroupController.php
Labels: Reviewed By PO

#278 Fix role access notification
  src/AppBundle/Controller/NotificationController.php
Labels: Reviewed By PO

#280 Responsive v2
  app/Resources/views/event/edit.html.twig
Labels: Reviewed By PO

#281 fin Erreur 404
  app/Resources/TwigBundle/views/Exception/error404.html.twig
  assets/scss/error404.scss
  webpack.config.js
Labels: Reviewed By PO

#282 participer à une édition
  app/Resources/views/edition/show.html.twig
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/User.php
Labels: Reviewed By PO

#283 Correction de l'affichage responsive de la vue user_invite
  app/Resources/views/user/invite.html.twig
  src/AppBundle/Form/InvitationType.php
Labels: Reviewed By PO

#277 S7 us46 navigation pills mon compte
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  assets/scss/main.scss
Labels: Reviewed By PO

#286 fix edition show alignement et ajout du bouton retour
  app/Resources/views/edition/show.html.twig
Labels: Reviewed By PO

#287 petite refacto
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/views/edition/show.html.twig
Labels: Reviewed By PO

#289 col 12
  app/Resources/views/edition/show.html.twig
Labels: Reviewed By PO

#290 Modifier le lien actif de la navbar en fonction de l'url
  app/Resources/views/base.html.twig
  assets/js/app.js
Labels: Reviewed By PO

#292 Je suis Arnaud et j'ai fait une faute
  app/Resources/views/event/proximity_events.html.twig
Labels: Reviewed By PO

#288 DevToMaster
  app/Resources/FOSUserBundle/views/Profile/edit_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/register_content.html.twig
  app/Resources/TwigBundle/views/Exception/error404.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/edition/show.html.twig
  app/Resources/views/event/edit.html.twig
  app/Resources/views/event/new.html.twig
  app/Resources/views/event/proximity_events.html.twig
  app/Resources/views/event/show.html.twig
  app/Resources/views/group/index.html.twig
  app/Resources/views/user/invite.html.twig
  assets/js/app.js
  assets/scss/error404.scss
  assets/scss/main.scss
  assets/scss/rangeStyle.scss
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/GroupController.php
  src/AppBundle/Controller/NotificationController.php
  src/AppBundle/Entity/Edition.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/InvitationType.php
  webpack.config.js
Labels: Reviewed By PO

#293 Ajout de classes bootstrap pour le responsive du récapitulatif du compte
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
Labels: Reviewed By PO

#294 fix responsive
  app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig
Labels: Reviewed By PO

#295 ajout de classes bootstrap pour le responsive
  app/Resources/FOSUserBundle/views/ChangePassword/change_password_content.html.twig
Labels: Reviewed By PO

#296 Fix bouton retour
  app/Resources/views/edition/new.html.twig
  app/Resources/views/edition/show.html.twig
Labels: Reviewed By PO

#297 fix bouton mobile
  app/Resources/views/user/invite.html.twig
Labels: Reviewed By PO

#298 Dev
  app/Resources/FOSUserBundle/views/ChangePassword/change_password_content.html.twig
  app/Resources/FOSUserBundle/views/Profile/show_content.html.twig
  app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig
  app/Resources/views/edition/new.html.twig
  app/Resources/views/edition/show.html.twig
  app/Resources/views/user/invite.html.twig
Labels: Reviewed By PO

#299 Fix after test team
  app/Resources/views/group/index.html.twig
  app/config/security.yml
  src/AppBundle/Controller/EditionController.php
  src/AppBundle/Controller/GroupController.php
  src/AppBundle/Controller/TaskController.php
  src/AppBundle/Controller/UserController.php
Labels: Reviewed By PO

#301 remplacement is defined par != null
  app/Resources/views/edition/show.html.twig
  app/Resources/views/event/show.html.twig
Labels: Reviewed By PO

#302 Correction check creator
  src/AppBundle/Controller/EditionController.php
Labels: Reviewed By PO

#303 Dev
  src/AppBundle/Controller/EditionController.php
Labels: Reviewed By PO

#304 Correction de l'affichage des icônes de media sociaux en format mobile
  app/Resources/views/footer.html.twig
  assets/scss/footer.scss
Labels: Reviewed By PO

#305 Dev
  app/Resources/views/footer.html.twig
  assets/scss/footer.scss
Labels: Reviewed By PO

#306 Readme
  README.md
  package.json
Labels: Reviewed By PO

#307 Dev
  README.md
  package.json
Labels: Reviewed By PO
